CREATE TABLE active_chats (
	
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL UNIQUE,
	host VARCHAR(16) NOT NULL,
	chatkey VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (id)
	
);

CREATE TABLE users_waiting (
	
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(16) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	fullname VARCHAR(100) NOT NULL,
	sessionkey VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (id)
	
);

CREATE TABLE events (
	
	id INT NOT NULL AUTO_INCREMENT,
	event_id INT NOT NULL,
	username VARCHAR(16) NOT NULL,
	occurred VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
	
);


CREATE TABLE invites (
	
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(16) NOT NULL,
	chatkey VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
	
);

CREATE TABLE participants (
	
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(16) NOT NULL,
	chatkey VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
	
);
